apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-kube
spec:
  selector:
    matchLabels:
      app: my-kube
  replicas: 2
  template:
    metadata:
      labels:
        app: my-kube
    spec:
      containers:
      - name: my-kube
        image: fotopiece/myweb:1.0
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-kube
spec:
  type: LoadBalancer
  selector:
    app: my-kube
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80